version: '2.3'
services:
  database:
    image: quay.io/azavea/postgis:2.2-postgres9.5-slim
    environment:
      - POSTGRES_USER=planit
      - POSTGRES_PASSWORD=planit
      - POSTGRES_DB=planit
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  angular:
    image: planit-spa
    build:
      context: ./src/angular
      dockerfile: Dockerfile
    volumes:
      - ./src/angular:/opt/planit/angular
    ports:
      - "4210:4210"

  django:
    image: planit-app
    build:
      context: ./src/django
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=database.service.planit.internal
      - POSTGRES_PORT=5432
      - POSTGRES_USER=planit
      - POSTGRES_PASSWORD=planit
      - POSTGRES_DB=planit
      - DJANGO_ENV=development
      - DJANGO_DEFAULT_FROM_EMAIL=planit@azavea.com
      - DJANGO_SECRET_KEY=secret
      - DJANGO_LOG_LEVEL=INFO
      - AWS_PROFILE=planit
    command:
      - "--workers=2"
      - "--timeout=60"
      - "--bind=0.0.0.0:8080"
      - "--reload"
      - "--log-level=debug"
      - "--access-logfile=-"
      - "--error-logfile=-"
      - "-kgevent"
      - "planit.wsgi"
    ports:
      - "8100:8080"
      - "8101:8081"
    links:
      - database:database.service.planit.internal
    volumes:
      - ./src/django:/usr/src
      - $HOME/.aws:/root/.aws:ro
